[project]
name = "stablecoin-quant"
version = "0.1.0"
description = ""
authors = [
    {name = "Axel Lode",email = "auj.lode@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib (>=3.10.6,<4.0.0)",
    "datetime (>=5.5,<6.0)",
    "pandas (>=2.3.2,<3.0.0)"
]

[project.optional-dependencies]
dev = [
    "black>=24.0.0",
    "ruff>=0.3.0",
    "mypy>=1.8.0",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.ruff]
line-length = 88
target-version = "py312"
select = ["E", "F", "I", "UP"]

[tool.mypy]
python_version = "3.12"
strict = true
