
initial_investment = 1000.0
yields_csv = "src/sample_yields.csv"

[csv]
path = "src/sample_pools.csv"
validation = "warn"
expected_frequency = ""
auto_refresh = false
refresh_url = ""

[filters]
min_tvl = 100000
min_base_apy = 0.06
auto_only = true
chains = []
stablecoins = []

[output]
outdir = "docs"
show = false
charts = ["bar", "scatter", "chain"]
history_charts = ["rolling_apy", "drawdowns", "realised_vs_target"]

[reporting]
top_n = 10
perf_fee_bps = 0.0
mgmt_fee_bps = 0.0
trading_cost_bps = 5.0

[reporting.history]
enabled = true
rolling_windows = [4, 12]
periods_per_year = 52
target_field = "net_apy"

[reporting.realised_apy_lookbacks]
"last 2 weeks" = "14D"
"last 52 weeks" = "52W"
