
csv = "src/sample_pools.csv"
min_tvl = 100000.0
min_base_apy = 0.06
auto_only = true
chains = ""
stablecoins = ""
charts = []
outdir = ""
fee_bps = 0.0
no_show = true

[csv]
path = "src/sample_pools.csv"

[filters]
min_tvl = 100000
min_base_apy = 0.06
auto_only = true
# chains = ["Ethereum", "Polygon"]
# stablecoins = ["USDC", "USDT"]

[output]
outdir = "outputs"
show = false
charts = ["bar", "scatter", "chain"]

[reporting]
top_n = 10
perf_fee_bps = 0.0
mgmt_fee_bps = 0.0

