name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: pages
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  lint:
    # Grant write access so the reusable pre-commit workflow can push auto-fixes on internal branches.
    permissions:
      contents: write
    uses: ./.github/workflows/pre-commit.yml
    with:
      python-version: '3.12'

  demo:
    needs: lint
    if: needs.lint.outputs.needs-autofix != 'true'
    uses: ./.github/workflows/demo.yml
    with:
      python-version: '3.12'
      artifact-name: demo-artifacts
      demo-outdir: demo_artifacts

  tests:
    needs: lint
    if: needs.lint.outputs.needs-autofix != 'true'
    uses: ./.github/workflows/tests.yml
    with:
      python-version: '3.12'
      coverage-xml-artifact: coverage-xml
      coverage-html-artifact: coverage-html

  deploy-coverage:
    needs: tests
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') && github.ref != 'refs/heads/gh-pages'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
