name: Codex Issue Analysis

on:
  issues:
    types: [opened, edited]

jobs:
  analyze-issue:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Analyze issue with Codex
        uses: actions/github-script@v7
        env:
          CODEX_API_URL: ${{ secrets.CODEX_API_URL }}
          CODEX_API_KEY: ${{ secrets.CODEX_API_KEY }}
        with:
          script: |
            const fetch = require('node-fetch');
            const res = await fetch(`${process.env.CODEX_API_URL}/issues`, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${process.env.CODEX_API_KEY}`
              },
              body: JSON.stringify({
                title: context.payload.issue.title,
                body: context.payload.issue.body
              })
            });
            core.info(await res.text());
