name: Codex Comment Resolution

# Triggered when new comments are added to issues for Codex follow-up.
on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  issue-resolution:
    if: github.event.comment.user.login != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Request Codex follow-up
        uses: ./.github/actions/codex-request
        with:
          github-token: ${{ github.token }}
          comment-body: |
            @codex please review the latest discussion.

            Summarize the thread, propose next actions, and flag owners who should respond.
          trigger-text: '@codex please review the latest discussion.'
