name: Codex Issue Analysis

# Triggered when issues are opened or edited to request Codex suggestions.
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  analyze-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Request Codex triage
        uses: actions/github-script@v7
        with:
          script: |
            const body = [
              '@codex please help triage this issue.',
              '',
              'Review the report, reproduce if possible, label severity, and outline next steps for the team.'
            ].join('\n');

            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body
            });
