name: Codex PR Review

# Triggered on pull request events to request Codex analysis.
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: read
  issues: write

jobs:
  review-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Request Codex review
        uses: actions/github-script@v7
        with:
          script: |
            const body = [
              '@codex please review this pull request.',
              '',
              'Focus on test coverage, correctness, security considerations, and any missing documentation.',
              'Share prioritized follow-up tasks for the maintainers.'
            ].join('\n');

            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body
            });
