name: Codex PR Review

# Triggered on pull request events to request Codex analysis.
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  review-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Request Codex review
        uses: ./.github/actions/codex-request
        with:
          github-token: ${{ github.token }}
          comment-body: |
            @codex please review this pull request.

            Focus on test coverage, correctness, security considerations, and any missing documentation.
            Share prioritized follow-up tasks for the maintainers.
          trigger-text: '@codex please review this pull request.'
          dedupe: true
