name: Codex Comment Resolution

# Triggered when new comments are added to issues for Codex follow-up.
on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  issue-resolution:
    if: github.event.comment.user.login != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Request Codex follow-up
        uses: actions/github-script@v7
        with:
          script: |
            const body = [
              '@codex please review the latest discussion.',
              '',
              'Summarize the thread, propose next actions, and flag owners who should respond.'
            ].join('\n');

            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body
            });
