name: Daily Demo Images

# Runs daily to refresh the published demo charts used for documentation assets.
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  generate-demo-images:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Generate demo artifacts
        env:
          MPLBACKEND: Agg
        run: |
          python src/stable_yield_demo.py configs/demo.toml

      - name: Upload demo images
        uses: actions/upload-artifact@v4
        with:
          name: daily-demo-images
          path: |
            docs/*.png
          if-no-files-found: error
