name: Daily Demo Images

# Runs daily to refresh the published demo charts used for documentation assets.
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  generate-demo-images:
    runs-on: ubuntu-latest
    env:
      DEMO_OUTDIR: demo_artifacts

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Generate demo artifacts
        env:
          MPLBACKEND: Agg
          STABLE_YIELD_OUTDIR: ${{ env.DEMO_OUTDIR }}
        run: |
          rm -rf "${STABLE_YIELD_OUTDIR}"
          python src/stable_yield_demo.py configs/demo.toml
          test -s "${STABLE_YIELD_OUTDIR}/bar_group_chain.png"
          if test -f "${STABLE_YIELD_OUTDIR}/scatter_risk_return.png"; then
            test -s "${STABLE_YIELD_OUTDIR}/scatter_risk_return.png"
          else
            test -s "${STABLE_YIELD_OUTDIR}/scatter_tvl_apy.png"
          fi
          test -s "${STABLE_YIELD_OUTDIR}/yield_vs_time.png"
          test -s "${STABLE_YIELD_OUTDIR}/nav_vs_time.png"

      - name: Upload demo artifacts
        uses: actions/upload-artifact@v4
        with:
          name: daily-demo-artifacts
          path: ${{ env.DEMO_OUTDIR }}
          if-no-files-found: error
