name: Daily Demo Images

# Runs daily to refresh the published demo charts used for documentation assets.
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  generate-demo-images:
    uses: ./.github/workflows/demo.yml
    with:
      python-version: '3.12'
      artifact-name: daily-demo-artifacts
      demo-outdir: demo_artifacts
